### ISSUE TITLE
Contact Validation

### ISSUE THREAD

**Issue by Greenjam94** [Greenjam94/tc359_rails_final#1]
Every field should have some kind of validation... right?
So don't forget about these: Address fields, facebook link, twitter link, company, job title, birthday, relationship, IM, Skype name, notes, public.

That's 11/18 fields going unvalidated

**Comment by Greenjam94** [comment]
Validated web links on dev site by copying valid_website.

**Comment by chrisvfritz** [comment]
Not *every* attribute necessarily needs validation, if we don't care if it's blank or about any other content it might contain. All that matters is that for each field, obviously bad data should not be allowed to be entered.
