### ISSUE TITLE
Travis CI Error

### ISSUE THREAD

**Issue by Greenjam94** [Greenjam94/tc359_rails_final#2]
Hi @chrisvfritz
I set up the yml.travis files to match what we had from the last time you helped me with Travis CI. Theres the database.yml.travis file and the .travis.yml file. For some reason the build is giving an error. I'm not sure why, I think it might be an issue with trying to create a test db? I'm not very good at reading the error output.

If you like, you can see that output for yourself at:
https://travis-ci.org/Greenjam94/tc359_rails_final/builds/58695610

**Comment by chrisvfritz** [comment]
Take a look at [this commit](https://github.com/Greenjam94/railsWithUser/commit/5bdd2e73040e2e63d9f1b3b71dd11cdb03ec2a85) from your other repo. I think making the same changes should fix it. Let me know how it goes!

Once it works by the way, I'll give you a point towards your final for Travis CI integration and create a skill for it on Codekwondo. :smiley:

**Comment by Greenjam94** [comment]
Well... it's not working, but we are one step closer! I guess I forgot to pull in your changes before I copied over the basics.

Now the error is when we try to deploy, I think it's invalid credentials? I even redid the Heroku secure API key like you showed me last time.
https://travis-ci.org/Greenjam94/tc359_rails_final/builds/58849189

**Comment by chrisvfritz** [comment]
Hmm... are you sure that you ran the key generation from your project folder?

**Comment by Greenjam94** [comment]
Positive, I even tried relogging into Heroku because I read some errors where Auth messed up.
```
James@MacbookAir:~/Documents/tc359/tc359_rails_final$ heroku login
Enter your Heroku credentials.
Email: Greenjam94@gmail.com
Password (typing will be hidden): 
Authentication successful.
James@MacbookAir:~/Documents/tc359/tc359_rails_final$ travis encrypt $(heroku auth:token)
Please add the following to your .travis.yml file:

  secure: "LUrVmK5XaQTJhfV7LYSMsc5I2X7ub3WO/ay1p/Bqo7YWGuD6VeGuOQcZzlDGGAA2abRQicOM7ps2IE8fXMlRZedRml8Oq8PzoecQiOoHjBLIfbGDj83kQICAnZmCGFqFGbaMvwrm5ve3eYZXcuPrqwTaC3A45WRQ4za/QFQoDJQ="

Pro Tip: You can add it automatically by running with --add.
```

**Comment by chrisvfritz** [comment]
Good thinking. When you just run heroku auth:token, does it seem to actually spit out a token or is it possible we're encrypting an error message? Long shot, but my idea bank is running low.

**Comment by Greenjam94** [comment]
It's an actual token: d1487258-####-####-9f7c-c75bf4cfcfe4 (I removed the middle 8 for security)

**Comment by Greenjam94** [comment]
It passed! Apperently travis tries to pull from origin remote when it shouldn't?

check out:
http://stackoverflow.com/questions/21978260/encrypted-key-unauthorized-for-continuous-deployment-travis-%E2%86%92-heroku

I ran this to get a new API key:
```
James@MacbookAir:~/Documents/tc359/tc359_rails_final$ travis encrypt -r Greenjam94/tc359_rails_final $(heroku auth:token)
Please add the following to your .travis.yml file:

  secure: "YMCcgnrtk77flN6I7AwdyufhDuhEJvlmTASkVwKN3zfyaNr1Gh60OYtWoc/XVorXxz4JGODjfSUfkT2prOYhbHhDfc/98GHqoCW8Og3hFdSGsyHKc1sG4tJMEkyvQZVUNQg4qNhN6gysCKH27nvc10+8TaIieNPuRrbGTpPouh8="

Pro Tip: You can add it automatically by running with --add.
```

**Comment by chrisvfritz** [comment]
Huh. Good to know! And great research. :+1: :tada:
