### ISSUE TITLE
(2) Use and organize SCSS in Rails

### ISSUE THREAD

**Issue by Greenjam94** [Greenjam94/tc359_rails_final#4]
@chrisvfritz I think this part is ready for review
 
 - There are only scss files in the stylesheets directory. 
 - application.scss is the only one in the root dir
 - I use compass and sass to make a gradient background for the website, since the background doesn't change it's in a base directory.
 - The colors are variables and the files are under 50 lines.
 - Auto-prefix gem is installed and bootstrap gem is using it already.

Thanks to http://compass-style.org/examples/compass/css3/gradient/

**Comment by chrisvfritz** [comment]
:+1: Looks good!
